### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by EduPH** [drexpp/Adversarial-examples-One-pixel-attack#1]
Hi! I think the link of the paper is:
https://arxiv.org/pdf/1710.08864.pdf

**Comment by drexpp** [comment]
Sorry my bad, I used the wrong link and didn't check it up.

I will send you an email today or tomorrow so we can have a meeting during this week (If it is possible) and talk about how is the attack and what is left to do (Mostly writing if the attack notebook is fine).

Thanks Eduardo.
